version: '3'
services:
  worker:
    environment:
      - APP_ENV=dev
      - APP_SECRET=vZkNnb2hxevZkNnb2hxevZkNnb2hxe
    container_name: 'corefiles'
    build:
      context: ./config/docker/dev/
      dockerfile: Dockerfile
    volumes:
       - corefiles-sync:/var/www/html:nocopy # nocopy is important
    ports:
      - 80:80
volumes:
  corefiles-sync:
    external: true


